import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:provider/provider.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  String _currentLanguage = 'en';

  String get currentLanguage => _currentLanguage;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('app_language') ?? 'en';
    notifyListeners();
  }

  Future<void> changeLanguage(String langCode) async {
    if (langCode == _currentLanguage) return;
    _currentLanguage = langCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', langCode);
    notifyListeners();
  }

  String translate(String key) {
    final translations = _localizedValues[_currentLanguage] ?? _localizedValues['en']!;
    return translations[key] ?? key;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'home': 'Home',
      'library': 'Library',
      'profile': 'Profile',
      'search_placeholder': 'Search songs, videos...',
      'no_internet': 'No internet connection',
      'offline_hint': 'Switch to the Library tab to listen to your downloaded offline files.',
      'offline_lib_btn': 'Offline Library',
      'load_error': 'Failed to load list or video not found.',
      'search_retry_hint': 'Please enter search keywords above or try the reload button below.',
      'try_again': 'Try again',
      'download': 'Download',
      'downloading': 'Downloading...',
      'downloaded': 'Downloaded',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'playing': 'Playing',
      'no_song': 'No song selected',
      'add_to_playlist': 'Add to Playlist',
      'create_playlist': 'Create Playlist',
      'playlist_name': 'Playlist name',
      'create': 'Create',
      'playlists': 'Playlists',
      'no_downloads': 'No downloads found',
      'no_downloads_hint': 'You have not downloaded any songs yet.',
      'logout': 'Sign Out',
      'total_downloads': 'Total downloads',
      'total_size': 'Total size',
      'clear_history': 'Clear history',
      'clear_rec_vectors': 'Clear recommendations',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'thai': 'ไทย',
      'lao': 'ລາວ',
      'guest': 'Guest',
      'mock_user': 'Mock User',
      'sign_in_google': 'Sign in with Google',
      'sign_in_mock': 'Sign in with Mock Demo',
      'sign_in_guest': 'Sign in as Guest',
      'welcome': 'Welcome to ThayTube',
      'welcome_subtitle': 'Your personal offline music and video player',
      'google_failed_snack': 'Could not connect Google Sign-In. Activating Demo Dev mode...',
      'playlist_empty': 'This playlist is empty',
      'play_all': 'Play All',
      'add_success': 'Added to playlist successfully',
      'history_cleared': 'Watch history cleared',
      'rec_cleared': 'Recommendation metrics reset',
      'audio_only': 'Audio Only',
      'video_mode': 'Video Mode',
      'download_started': 'Download started...',
      'download_failed': 'Download failed',
      'download_success': 'Downloaded successfully',
      'download_cancelled': 'Download cancelled',
      'already_downloaded': 'Already downloaded',
      'remove_download': 'Remove Download',
      'remove_download_confirm': 'Are you sure you want to remove this download?',
      'yes': 'Yes',
      'no': 'No',
      // New localized strings:
      'audio_stream_online': 'Stream Audio Online',
      'playing_online': 'Playing online: ',
      'download_video_offline': 'Download Video Offline (Video + Audio)',
      'download_audio_offline': 'Download Audio Offline (Audio Only)',
      'select_video_quality': 'Select Video Quality',
      'select_audio_quality': 'Select Audio Quality',
      'error_get_quality': 'Failed to get stream qualities',
      'no_quality_options': 'No suitable quality options found.',
      'format': 'Format',
      'video': 'Video',
      'audio': 'Audio',
      'storage_stats': 'Storage Stats',
      'favorite_list': 'Favorites',
      'play_history': 'Play History',
      'files': 'files',
      'search_downloads_placeholder': 'Search downloaded files...',
      'all': 'All',
      'no_matching_downloads': 'No matching downloaded files found.',
      'no_playlists': 'No playlists yet',
      'create_playlist_hint': 'Create playlists to organize your favorite tracks',
      'no_matching_playlists': 'No matching playlists found.',
      'songs': 'songs',
      'delete_playlist': 'Delete Playlist',
      'delete_playlist_confirm': 'Are you sure you want to delete playlist',
      'file_error': '(File Error)',
      'deleted': 'Deleted',
      'no_track_playing': 'No track playing',
      'now_playing': 'NOW PLAYING',
      'empty_playlist_hint': 'No tracks in this playlist.\nAdd tracks from offline library or the player.',
      'removed_from_playlist': 'Removed from playlist',
      'create_new_playlist': 'Create new playlist',
      'no_playlists_create': 'No playlists yet. Create one!',
      'song_already_in_playlist': 'This track is already in this playlist!',
      'playlist_description': 'Description (optional)',
      'playlist_created': 'Created playlist',
      'video_play_error': 'Cannot play this video. The file might be corrupted.',
      'loading_video': 'Loading video...',
      'fetching_video_details': 'Fetching video details...',
      'preparing': 'Preparing...',
      'fetching_streams': 'Fetching streams...',
      'downloading_media': 'Downloading media...',
      'saving_artwork': 'Saving artwork...',
      'retrying_fallback': 'Retrying with fallback...',
      'waiting_queue': 'Waiting in queue...',
      'export_backup': 'Export Backup',
      'export_backup_desc': 'Save downloads, playlists to a file',
      'export_success': '✅ Backup exported successfully!',
      'restore_backup': 'Restore Backup',
      'restore_backup_desc': 'Import backup file to restore data',
      'edit_name': 'Edit Name',
      'enter_name_hint': 'Enter your name',
      'save': 'Save',
      'paste_backup_path': 'Paste path to thaytube_backup.json:',
      'restore_confirm_desc': 'Select your backup JSON file to proceed. Current data will be overwritten and the app will restart.',
      'restart_warning': '⚠️ App needs to restart for changes to take effect.',
      'restore_success': '✅ Restore successful! Please restart the app.',
      'tap_to_edit': 'Tap name or photo to edit',
      'general_settings': 'General Settings',
      'data_backup': 'Data & Backup',
      'restore': 'Restore',
    },
    'vi': {
      'home': 'Trang chủ',
      'library': 'Thư viện',
      'profile': 'Cá nhân',
      'search_placeholder': 'Tìm kiếm bài hát, video...',
      'no_internet': 'Không có kết nối mạng',
      'offline_hint': 'Hãy chuyển sang mục Thư viện để nghe và xem những file nhạc, video bạn đã tải về offline.',
      'offline_lib_btn': 'Thư viện Offline',
      'load_error': 'Không tải được danh sách hoặc không tìm thấy video.',
      'search_retry_hint': 'Bạn hãy nhập từ khóa tìm kiếm ở thanh trên cùng hoặc thử bấm nút tải lại bên dưới.',
      'try_again': 'Thử tải lại',
      'download': 'Tải về',
      'downloading': 'Đang tải về...',
      'downloaded': 'Đã tải',
      'delete': 'Xóa',
      'cancel': 'Hủy',
      'playing': 'Đang phát',
      'no_song': 'Chưa chọn bài hát nào',
      'add_to_playlist': 'Thêm vào Playlist',
      'create_playlist': 'Tạo Playlist',
      'playlist_name': 'Tên danh sách phát',
      'create': 'Tạo',
      'playlists': 'Playlist',
      'no_downloads': 'Chưa tải file nào',
      'no_downloads_hint': 'Bạn chưa tải bài hát nào về máy.',
      'logout': 'Đăng xuất tài khoản',
      'total_downloads': 'Số file đã tải',
      'total_size': 'Dung lượng',
      'clear_history': 'Xóa lịch sử xem',
      'clear_rec_vectors': 'Đặt lại đề xuất',
      'settings': 'Cài đặt ứng dụng',
      'language': 'Ngôn ngữ',
      'select_language': 'Chọn ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'thai': 'ไทย',
      'lao': 'ລາວ',
      'guest': 'Khách',
      'mock_user': 'Người dùng Demo',
      'sign_in_google': 'Đăng nhập bằng Google',
      'sign_in_mock': 'Đăng nhập với TK Demo (Bỏ qua)',
      'sign_in_guest': 'Tiếp tục với vai trò Khách',
      'welcome': 'Chào mừng đến với ThayTube',
      'welcome_subtitle': 'Trình phát nhạc và video offline cá nhân của bạn',
      'google_failed_snack': 'Không thể kết nối Google Sign-In. Đang bật chế độ Demo Dev...',
      'playlist_empty': 'Danh sách phát này đang trống',
      'play_all': 'Phát tất cả',
      'add_success': 'Đã thêm vào danh sách phát thành công',
      'history_cleared': 'Đã xóa lịch sử xem',
      'rec_cleared': 'Đã đặt lại thuật toán gợi ý',
      'audio_only': 'Chỉ nghe nhạc',
      'video_mode': 'Xem Video',
      'download_started': 'Bắt đầu tải xuống...',
      'download_failed': 'Tải xuống thất bại',
      'download_success': 'Tải xuống thành công',
      'download_cancelled': 'Đã hủy tải xuống',
      'already_downloaded': 'Đã tải về trước đó',
      'remove_download': 'Xóa tải xuống',
      'remove_download_confirm': 'Bạn có chắc chắn muốn xóa tệp đã tải xuống này?',
      'yes': 'Có',
      'no': 'Không',
      // New localized strings:
      'audio_stream_online': 'Phát nhạc trực tuyến (Audio Stream)',
      'playing_online': 'Đang phát online: ',
      'download_video_offline': 'Tải Video Offline (Video + Audio)',
      'download_audio_offline': 'Tải Nhạc Offline (Chỉ âm thanh)',
      'select_video_quality': 'Chọn chất lượng Video',
      'select_audio_quality': 'Chọn chất lượng Nhạc',
      'error_get_quality': 'Không thể lấy thông tin chất lượng',
      'no_quality_options': 'Không có tùy chọn chất lượng nào phù hợp.',
      'format': 'Định dạng',
      'video': 'Video',
      'audio': 'Audio',
      'storage_stats': 'Thống kê bộ nhớ',
      'favorite_list': 'Danh sách yêu thích',
      'play_history': 'Lịch sử phát',
      'files': 'file',
      'search_downloads_placeholder': 'Tìm kiếm tệp tải xuống...',
      'all': 'Tất cả',
      'no_matching_downloads': 'Không tìm thấy tệp tải xuống phù hợp.',
      'no_playlists': 'Chưa có playlist nào',
      'create_playlist_hint': 'Tạo playlist để lưu trữ các bài hát yêu thích',
      'no_matching_playlists': 'Không tìm thấy playlist phù hợp.',
      'songs': 'bài hát',
      'delete_playlist': 'Xóa Playlist',
      'delete_playlist_confirm': 'Bạn có chắc muốn xóa playlist',
      'file_error': '(File lỗi)',
      'deleted': 'Đã xóa',
      'no_track_playing': 'Không có bài hát đang phát',
      'now_playing': 'ĐANG PHÁT',
      'empty_playlist_hint': 'Chưa có bài hát nào trong playlist.\nHãy thêm bài hát từ thư viện hoặc màn hình phát.',
      'removed_from_playlist': 'Đã xóa khỏi playlist',
      'create_new_playlist': 'Tạo Playlist mới',
      'no_playlists_create': 'Chưa có playlist nào. Hãy tạo mới!',
      'song_already_in_playlist': 'Bài hát đã có sẵn trong playlist này!',
      'playlist_description': 'Mô tả (không bắt buộc)',
      'playlist_created': 'Đã tạo playlist',
      'video_play_error': 'Không thể phát video này. Tệp có thể bị lỗi.',
      'loading_video': 'Đang tải video...',
      'fetching_video_details': 'Đang lấy thông tin video...',
      'preparing': 'Đang chuẩn bị...',
      'fetching_streams': 'Đang lấy dữ liệu luồng...',
      'downloading_media': 'Đang tải tệp tin...',
      'saving_artwork': 'Đang lưu ảnh đại diện...',
      'retrying_fallback': 'Đang thử lại với luồng dự phòng...',
      'waiting_queue': 'Đang xếp hàng chờ...',
      'export_backup': 'Xuất Backup',
      'export_backup_desc': 'Lưu danh sách tải, playlist ra file',
      'export_success': '✅ Xuất backup thành công!',
      'restore_backup': 'Khôi phục Backup',
      'restore_backup_desc': 'Nhập file backup để khôi phục dữ liệu',
      'edit_name': 'Chỉnh sửa tên',
      'enter_name_hint': 'Nhập tên của bạn',
      'save': 'Lưu',
      'paste_backup_path': 'Dán đường dẫn đến file thaytube_backup.json:',
      'restore_confirm_desc': 'Chọn tệp backup JSON để tiến hành. Dữ liệu hiện tại sẽ bị ghi đè và ứng dụng sẽ khởi động lại.',
      'restart_warning': '⚠️ Ứng dụng sẽ cần khởi động lại để dữ liệu có hiệu lực.',
      'restore_success': '✅ Khôi phục thành công! Vui lòng khởi động lại ứng dụng.',
      'tap_to_edit': 'Nhấn vào tên hoặc ảnh để chỉnh sửa',
      'general_settings': 'Cài đặt chung',
      'data_backup': 'Dữ liệu & Sao lưu',
      'restore': 'Khôi phục',
    },
    'th': {
      'home': 'หน้าแรก',
      'library': 'คลังเพลง',
      'profile': 'โปรไฟล์',
      'search_placeholder': 'ค้นหาเพลง วิดีโอ...',
      'no_internet': 'ไม่มีการเชื่อมต่ออินเทอร์เน็ต',
      'offline_hint': 'สลับไปยังแท็บคลังเพลงเพื่อฟังและดูไฟล์เพลงและวิดีโอที่คุณดาวน์โหลดไว้แบบออฟไลน์',
      'offline_lib_btn': 'คลังเพลงออฟไลน์',
      'load_error': 'ไม่สามารถโหลดรายการหรือหาวิดีโอไม่พบ',
      'search_retry_hint': 'กรุณาป้อนคำค้นหาด้านบนหรือลองปุ่มโหลดซ้ำด้านล่าง',
      'try_again': 'โหลดใหม่',
      'download': 'ดาวน์โหลด',
      'downloading': 'กำลังดาวน์โหลด...',
      'downloaded': 'ดาวน์โหลดแล้ว',
      'delete': 'ลบ',
      'cancel': 'ยกเลิก',
      'playing': 'กำลังเล่น',
      'no_song': 'ยังไม่ได้เลือกเพลง',
      'add_to_playlist': 'เพิ่มในเพลย์ลิสต์',
      'create_playlist': 'สร้างเพลย์ลิสต์',
      'playlist_name': 'ชื่อเพลย์ลิสต์',
      'create': 'สร้าง',
      'playlists': 'เพลย์ลิสต์',
      'no_downloads': 'ไม่พบไฟล์ดาวน์โหลด',
      'no_downloads_hint': 'คุณยังไม่ได้ดาวน์โหลดเพลงใดๆ',
      'logout': 'ออกจากระบบบัญชี',
      'total_downloads': 'ดาวน์โหลดทั้งหมด',
      'total_size': 'ขนาดทั้งหมด',
      'clear_history': 'ล้างประวัติการดู',
      'clear_rec_vectors': 'รีเซ็ตคำแนะนำ',
      'settings': 'การตั้งค่าแอพ',
      'language': 'ภาษา',
      'select_language': 'เลือกภาษา',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'thai': 'ไทย',
      'lao': 'ລາວ',
      'guest': 'ผู้เยี่ยมชม',
      'mock_user': 'ผู้ใช้จำลอง',
      'sign_in_google': 'เข้าสู่ระบบด้วย Google',
      'sign_in_mock': 'เข้าสู่ระบบด้วยบัญชีเดโม',
      'sign_in_guest': 'ดำเนินการต่อในฐานะผู้เยี่ยมชม',
      'welcome': 'ยินดีต้อนรับสู่ ThayTube',
      'welcome_subtitle': 'เครื่องเล่นเพลงและวิดีโอออฟไลน์ส่วนตัวของคุณ',
      'google_failed_snack': 'ไม่สามารถเชื่อมต่อ Google Sign-In กำลังเปิดใช้งานโหมดเดโม...',
      'playlist_empty': 'เพลย์ลิสต์นี้ว่างเปล่า',
      'play_all': 'เล่นทั้งหมด',
      'add_success': 'เพิ่มในเพลย์ลิสต์เรียบร้อยแล้ว',
      'history_cleared': 'ล้างประวัติการรับชมแล้ว',
      'rec_cleared': 'รีเซ็ตตัวชี้วัดคำแนะนำแล้ว',
      'audio_only': 'ฟังเพลงอย่างเดียว',
      'video_mode': 'โหมดวิดีโอ',
      'download_started': 'เริ่มดาวน์โหลด...',
      'download_failed': 'ดาวน์โหลดล้มเหลว',
      'download_success': 'ดาวน์โหลดสำเร็จ',
      'download_cancelled': 'ยกเลิกการดาวน์โหลด',
      'already_downloaded': 'ดาวน์โหลดแล้วก่อนหน้านี้',
      'remove_download': 'ลบไฟล์ดาวน์โหลด',
      'remove_download_confirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบไฟล์ดาวน์โหลดนี้?',
      'yes': 'ใช่',
      'no': 'ไม่',
      // New localized strings:
      'audio_stream_online': 'เล่นเพลงออนไลน์ (Audio Stream)',
      'playing_online': 'กำลังเล่นออนไลน์: ',
      'download_video_offline': 'ดาวน์โหลดวิดีโอออฟไลน์ (วิดีโอ + เสียง)',
      'download_audio_offline': 'ดาวน์โหลดเสียงออฟไลน์ (เฉพาะเสียง)',
      'select_video_quality': 'เลือกคุณภาพวิดีโอ',
      'select_audio_quality': 'เลือกคุณภาพเสียง',
      'error_get_quality': 'ไม่สามารถดึงข้อมูลคุณภาพสตรีมได้',
      'no_quality_options': 'ไม่พบตัวเลือกคุณภาพที่เหมาะสม',
      'format': 'รูปแบบ',
      'video': 'วิดีโอ',
      'audio': 'เสียง',
      'storage_stats': 'สถิติการจัดเก็บข้อมูล',
      'favorite_list': 'รายการโปรด',
      'play_history': 'ประวัติการเล่น',
      'files': 'ไฟล์',
      'search_downloads_placeholder': 'ค้นหาไฟล์ที่ดาวน์โหลด...',
      'all': 'ทั้งหมด',
      'no_matching_downloads': 'ไม่พบไฟล์ดาวน์โหลดที่ตรงกัน',
      'no_playlists': 'ยังไม่มีเพลย์ลิสต์',
      'create_playlist_hint': 'สร้างเพลย์ลิสต์เพื่อจัดระเบียบเพลงโปรดของคุณ',
      'no_matching_playlists': 'ไม่พบเพลย์ลิสต์ที่ตรงกัน',
      'songs': 'เพลง',
      'delete_playlist': 'ลบเพลย์ลิสต์',
      'delete_playlist_confirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบเพลย์ลิสต์',
      'file_error': '(ไฟล์เสีย)',
      'deleted': 'ลบแล้ว',
      'no_track_playing': 'ไม่มีเพลงที่กำลังเล่นอยู่',
      'now_playing': 'กำลังเล่น',
      'empty_playlist_hint': 'ยังไม่มีเพลงในเพลย์ลิสต์นี้\nเพิ่มเพลงจากคลังออฟไลน์หรือหน้าจอเครื่องเล่น',
      'removed_from_playlist': 'ลบออกจากเพลย์ลิสต์แล้ว',
      'create_new_playlist': 'สร้างเพลย์ลิสต์ใหม่',
      'no_playlists_create': 'ยังไม่มีเพลย์ลิสต์ ลองสร้างดูสิ!',
      'song_already_in_playlist': 'เพลงนี้มีอยู่ในเพลย์ลิสต์นี้แล้ว!',
      'playlist_description': 'คำอธิบาย (ไม่บังคับ)',
      'playlist_created': 'สร้างเพลย์ลิสต์แล้ว',
      'video_play_error': 'ไม่สามารถเล่นวิดีโอนี้ได้ ไฟล์อาจจะเสีย',
      'loading_video': 'กำลังโหลดวิดีโอ...',
      'fetching_video_details': 'กำลังดึงข้อมูลวิดีโอ...',
      'preparing': 'กำลังเตรียมการ...',
      'fetching_streams': 'กำลังดึงสตรีม...',
      'downloading_media': 'กำลังดาวน์โหลดไฟล์...',
      'saving_artwork': 'กำลังบันทึกหน้าปก...',
      'retrying_fallback': 'กำลังลองใหม่ด้วยสตรีมสำรอง...',
      'waiting_queue': 'กำลังรอในคิว...',
      'export_backup': 'ส่งออกข้อมูลสำรอง',
      'export_backup_desc': 'บันทึกรายการดาวน์โหลดและเพลย์ลิสต์ลงไฟล์',
      'export_success': '✅ ส่งออกข้อมูลสำรองสำเร็จแล้ว!',
      'restore_backup': 'นำเข้าข้อมูลสำรอง',
      'restore_backup_desc': 'นำเข้าไฟล์สำรองเพื่อกู้คืนข้อมูล',
      'edit_name': 'แก้ไขชื่อ',
      'enter_name_hint': 'ใส่ชื่อของคุณ',
      'save': 'บันทึก',
      'paste_backup_path': 'วางเส้นทางไปที่ไฟล์ thaytube_backup.json:',
      'restore_confirm_desc': 'เลือกไฟล์สำรองข้อมูล JSON เพื่อดำเนินการต่อ ข้อมูลปัจจุบันจะถูกแทนที่และแอพจะรีสตาร์ท',
      'restart_warning': '⚠️ แอพจำเป็นต้องรีสตาร์ทเพื่อให้ข้อมูลมีผล',
      'restore_success': '✅ กู้คืนข้อมูลสำเร็จ! กรุณารีสตาร์ทแอพ',
      'tap_to_edit': 'แตะที่ชื่อหรือรูปภาพเพื่อแก้ไข',
      'general_settings': 'การตั้งค่าทั่วไป',
      'data_backup': 'ข้อมูลและการสำรองข้อมูล',
      'restore': 'กู้คืน',
    },
    'lo': {
      'home': 'ໜ້າທຳອິດ',
      'library': 'ຄັງເພງ',
      'profile': 'ໂປຣຟາຍ',
      'search_placeholder': 'ຄ້ນຫາເພງ, ວິດີໂອ...',
      'no_internet': 'ບໍ່ມີການເຊື່ອມຕໍ່ອິນເຕີເນັດ',
      'offline_hint': 'ສະຫຼັບໄປແຖບຄັງເພງເພື່ອຟັງແລະເບິ່ງໄຟລ໌ເພງແລະວິດີໂອທີ່ທ່ານດາວໂຫລດໄວ້ແບບອອບລາຍ.',
      'offline_lib_btn': 'ຄັງເພງອອບລາຍ',
      'load_error': 'ບໍ່ສາມາດໂຫຼດລາຍການ ຫຼື ຫາວິດີໂອບໍ່ເຫັນ',
      'search_retry_hint': 'ກະລຸນາປ້ອນຄຳຄົ້ນຫາດ້ານເທິງ ຫຼື ລອງປຸ່ມໂຫຼດຄືນໃໝ່ດ້ານລຸ່ມ',
      'try_again': 'ໂຫຼດຄືນໃໝ່',
      'download': 'ດາວໂຫລດ',
      'downloading': 'ກຳລັງດາວໂຫລດ...',
      'downloaded': 'ດາວໂຫລດແລ້ວ',
      'delete': 'ລົບ',
      'cancel': 'ຍົກເລີກ',
      'playing': 'ກຳລັງຫຼິ້ນ',
      'no_song': 'ຍັງບໍ່ໄດ້ເລືອກເພງ',
      'add_to_playlist': 'ເພີ່ມໃສ່ລາຍການຫຼິ້ນ',
      'create_playlist': 'ສ້າງລາຍການຫຼິ້ນ',
      'playlist_name': 'ຊື່ລາຍການຫຼິ້ນ',
      'create': 'ສ້າງ',
      'playlists': 'ລາຍການຫຼິ້ນ',
      'no_downloads': 'ບໍ່ພົບໄຟລ໌ດາວໂຫລດ',
      'no_downloads_hint': 'ທ່ານຍັງບໍ່ໄດ້ດາວໂຫລດເພງໃດໆ.',
      'logout': 'ອອກຈາກລະບົບບັນຊີ',
      'total_downloads': 'ດາວໂຫລດທັງໝົດ',
      'total_size': 'ຂະໜາດທັງໝົດ',
      'clear_history': 'ລ້າງປະຫວັດການເບິ່ງ',
      'clear_rec_vectors': 'ຣີເຊັດຄຳແນະນຳ',
      'settings': 'ການຕັ້ງຄ່າແອັບ',
      'language': 'ພາສາ',
      'select_language': 'ເລືອກພາສາ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'thai': 'ไทย',
      'lao': 'ລາວ',
      'guest': 'ຜູ້ຢ້ຽມຊົມ',
      'mock_user': 'ຜູ້ໃຊ້ຈຳລອງ',
      'sign_in_google': 'ເຂົ້າສູ່ລະບົບດ້ວຍ Google',
      'sign_in_mock': 'ເຂົ້າສູ່ລະບົບດ້ວຍບັນຊີເດໂມ',
      'sign_in_guest': 'ດຳເນີນການຕໍ່ໃນຖານະຜູ້ຢ້ຽມຊົມ',
      'welcome': 'ຍິນດີຕ້ອນຮັບສູ່ ThayTube',
      'welcome_subtitle': 'ເຄື່ອງຫຼິ້ນເພງ ແລະ ວິດີໂອອອບລາຍສ່ວນຕົວຂອງທ່ານ',
      'google_failed_snack': 'ບໍ່ສາມາດເຊື່ອມຕໍ່ Google Sign-In ກຳລັງເປີດໃຊ້ງານໂໝດເດໂມ...',
      'playlist_empty': 'ລາຍການຫຼິ້ນນີ້ວ່າງເປົ່າ',
      'play_all': 'ຫຼິ້ນທັງໝົດ',
      'add_success': 'ເພີ່ມໃສ່ລາຍการຫຼິ້ນສຳເລັດແລ້ວ',
      'history_cleared': 'ລ້າງປະຫວັດການເບິ່ງແລ້ວ',
      'rec_cleared': 'ຣີເຊັດການແນະນຳແລ້ວ',
      'audio_only': 'ຟັງເພງຢ່າງດຽວ',
      'video_mode': 'ໂໝດວິດີໂອ',
      'download_started': 'ເລີ່ມດາວໂຫລດ...',
      'download_failed': 'ດາວໂຫລດຫຼົ້ມເຫຼວ',
      'download_success': 'ດາວໂຫລດສຳເລັດ',
      'download_cancelled': 'ຍົກເລີກການດາວໂຫລດ',
      'already_downloaded': 'ດາວໂຫລດແລ້ວກ່ອນໜ້ານີ້',
      'remove_download': 'ລົບໄຟລ໌ດາວໂຫລດ',
      'remove_download_confirm': 'ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບໄຟລ໌ດາວໂຫລດນີ້?',
      'yes': 'ແມ່ນ',
      'no': 'ບໍ່',
      // New localized strings:
      'audio_stream_online': 'ຫຼິ້ນເພງອອນລາຍ (Audio Stream)',
      'playing_online': 'ກຳລັງຫຼິ້ນອອນລາຍ: ',
      'download_video_offline': 'ດາວໂຫລດວິດີໂອອອບລาย (ວິດີໂອ + ສຽງ)',
      'download_audio_offline': 'ດາວໂຫລດສຽງອອບລາຍ (ສະເພາະສຽງ)',
      'select_video_quality': 'ເລືອກຄຸນນະພາບວິດີໂອ',
      'select_audio_quality': 'ເລືອກຄຸນນະພາບສຽງ',
      'error_get_quality': 'ບໍ່ສາມາດດຶງຂໍ້ມູນຄຸນນະພາບສະຕຣີມໄດ້',
      'no_quality_options': 'ບໍ່ພົບຕົວເລືອກຄຸນນະພາບທີ່ເໝາະສົມ',
      'format': 'ຮູບແບບ',
      'video': 'ວິດີໂອ',
      'audio': 'ສຽງ',
      'storage_stats': 'ສະຖິຕິການເກັບຂໍ້ມູນ',
      'favorite_list': 'ລາຍການທີ່ມັກ',
      'play_history': 'ປະຫວັດການຫຼິ້ນ',
      'files': 'ໄຟລ໌',
      'search_downloads_placeholder': 'ຄົ້ນຫາໄຟລ໌ທີ່ດາວໂຫລດ...',
      'all': 'ທັງໝົດ',
      'no_matching_downloads': 'ບໍ່ພົບໄຟລ໌ດາວໂຫລດທີ່ກົງກັນ',
      'no_playlists': 'ຍັງບໍ່ມີລາຍການຫຼິ້ນ',
      'create_playlist_hint': 'ສ້າງລາຍການຫຼິ້ນເພື່ອຈັດລະບຽບເພງທີ່ທ່ານມັກ',
      'no_matching_playlists': 'ບໍ່ພົບລາຍການຫຼິ້ນທີ່ກົງກັນ',
      'songs': 'ເພງ',
      'delete_playlist': 'ລົບລາຍການຫຼິ້ນ',
      'delete_playlist_confirm': 'ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບລາຍການຫຼິ້ນ',
      'file_error': '(ໄຟລ໌ເສຍ)',
      'deleted': 'ລົບແລ້ວ',
      'no_track_playing': 'ບໍ່ມີເພງທີ່ກຳລັງຫຼິ້ນ',
      'now_playing': 'ກຳລັງຫຼິ້ນ',
      'empty_playlist_hint': 'ຍັງບໍ່ມີເພງໃນລາຍການຫຼິ້ນນີ້\nເພີ່ມເພງຈາກຄັງອອບລາຍຫຼືໜ້າຈໍເຄື່ອງຫຼິ້ນ',
      'removed_from_playlist': 'ລົບອອກຈາກລາຍການຫຼิ້ນແລ້ວ',
      'create_new_playlist': 'ສ້າງລາຍການຫຼິ້ນໃໝ່',
      'no_playlists_create': 'ຍັງບໍ່ມີລາຍການຫຼິ້ນ ເລີ່ມສ້າງເລີຍ!',
      'song_already_in_playlist': 'ເພງນີ້ມີຢູ່ໃນລາຍການຫຼິ້ນນີ້ແລ້ວ!',
      'playlist_description': 'ຄຳອະທິບາຍ (ບໍ່ບັງຄັບ)',
      'playlist_created': 'ສ້າງລາຍການຫຼິ້ນແລ້ວ',
      'video_play_error': 'ບໍ່ສາມາດຫຼິ້ນວິດີໂອນີ້ໄດ້ ໄຟລ໌ອາດຈະເສຍ',
      'loading_video': 'ກຳລັງໂຫຼດວິດີໂອ...',
      'fetching_video_details': 'ກຳລັງດຶງຂໍ້ມູນວິດີໂອ...',
      'preparing': 'ກຳລັງກະກຽມ...',
      'fetching_streams': 'ກຳລັງດຶງຂໍ້ມູນ...',
      'downloading_media': 'ກຳລັງດາວໂຫລດ...',
      'saving_artwork': 'ກຳລັງບັນທຶກຮູບ...',
      'retrying_fallback': 'ກຳລັງລອງໃໝ່ດ້ວຍຂໍ້ມູນສຳຮອງ...',
      'waiting_queue': 'ຢູ່ໃນຄິວລໍຖ້າ...',
      'export_backup': 'ສົ່ງອອກຂໍ້ມູນສຳຮອງ',
      'export_backup_desc': 'ບັນທຶກລາຍການດາວໂຫລດແລະເພລລິສລົງໄຟລ໌',
      'export_success': '✅ ສົ່ງອອກຂໍ້ມູນສຳຮອງສຳເລັດແລ້ວ!',
      'restore_backup': 'ນຳເຂົ້າຂໍ້ມູນສຳຮອງ',
      'restore_backup_desc': 'ນຳເຂົ້າໄຟລ໌ສຳຮອງເພື່ອກູ້ຄືນຂໍ້ມູນ',
      'edit_name': 'ແກ້ໄຂຊື່',
      'enter_name_hint': 'ໃສ່ຊື່ຂອງທ່ານ',
      'save': 'ບັນທຶກ',
      'paste_backup_path': 'ວາງເສັ້ນທາງໄປຫາໄຟລ໌ thaytube_backup.json:',
      'restore_confirm_desc': 'ເລືອກໄຟລ໌ສຳຮອງຂໍ້ມູນ JSON ເພື່ອດຳເນີນການຕໍ່ ຂັ້ນຕອນນີ້ຈະຂຽນທັບຂໍ້ມູນປັດຈຸບັນ ແລະ ແອັບຈະຣີສະຕາດ',
      'restart_warning': '⚠️ ແອັບຈຳເປັນຕ້ອງຣີສະຕາດເພື່ອໃຫ້ຂໍ້ມູນມີຜົນ',
      'restore_success': '✅ ກູ້ຄືນຂໍ້ມູນສຳເລັດ! ກະລຸນາຣີສະຕາດແອັບ',
      'tap_to_edit': 'ແຕະທີ່ຊື່ ຫຼື ຮູບພາບເພື່ອແກ້ໄຂ',
      'general_settings': 'ການຕັ້ງຄ່າທົ່ວໄປ',
      'data_backup': 'ຂໍ້ມູນແລະການສຳຮອງຂໍ້ມູນ',
      'restore': 'ກູ້ຄືນ',
    }
  };
}

extension LocalizationExtension on BuildContext {
  String tr(String key) {
    return Provider.of<LanguageService>(this).translate(key);
  }
}
